# NVEnc
# continuous integration settings

image: Visual Studio 2015

platform:
 - Win32
 - x64

configuration:
 - RelStatic

branches:
  only:
    - master

skip_non_tags: true

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive
  - mkdir c:\yasm
  - if "%PLATFORM%" == "x64"   curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - if "%PLATFORM%" == "Win32" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe
  - set PATH=c:\yasm;%PATH%
  - yasm --version

before_build:
  - appveyor DownloadFile https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda_8.0.44_windows-exe -FileName cuda_8.0.44_windows.exe
  - cuda_8.0.44_windows.exe -s compiler_8.0 command_line_tools_8.0 cudart_8.0 curand_8.0 curand_dev_8.0 npp_8.0 npp_dev_8.0 nvml_dev_8.0 visual_studio_integration_8.0
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;%PATH%
  - set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0
  - set CUDA_PATH_V8_0=%CUDA_PATH%
  - git clone https://github.com/vapoursynth/vapoursynth.git ..\vapoursynth
  - git clone -b MT https://github.com/pinterf/AviSynthPlus.git ..\avisynthplus
  - for /f "usebackq tokens=*" %%i IN (`cd`) DO @set CURRENT_DIR=%%i
  - set AVISYNTH_SDK=%CURRENT_DIR%\..\AviSynthPlus\avs_core
  - set VAPOURSYNTH_SDK=%CURRENT_DIR%\..\vapoursynth
  - echo %CURRENT_DIR%
  - echo %PLATFORM%
  - echo %CONFIGURATION%
  - echo %AVISYNTH_SDK%
  - echo %VAPOURSYNTH_SDK%
  - ps: |
      $version = $null
      if (Test-Path Env:APPVEYOR_REPO_TAG_NAME)
      {
          $version = (Get-Item Env:APPVEYOR_REPO_TAG_NAME).Value
      }
      
      if ([string]::IsNullOrEmpty($version))
      {
          $version = $env:APPVEYOR_BUILD_VERSION + '_Alpha'
      }
      $env:BUILD_VERSION=$version

  - echo %BUILD_VERSION%
  - appveyor UpdateBuild -Version "%BUILD_VERSION%"

build:
  parallel: true
  project: NVEnc.sln

after_build:
  - mkdir NVEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\NVEncC*.exe NVEncC_Release
  - copy _build\%PLATFORM%\%CONFIGURATION%\*.dll NVEncC_Release
  - 7z a -mx9 NVEncC_%BUILD_VERSION%_%PLATFORM%.7z .\NVEncC_Release\*

artifacts:
  - path: NVEncC_%BUILD_VERSION%_%PLATFORM%.7z
    name: NVEncC_%BUILD_VERSION%_%PLATFORM%

deploy:
  provider: GitHub
  auth_token:
    secure: IDRwZWN1uQaTxb64SQnTDNJR5KPtCFPL3Mln9GrdZ7TSiyec/o1KXpOuh/50ZO5A
  artifact: NVEncC_%BUILD_VERSION%_%PLATFORM%
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
